spring.application.name=quiz-service
spring.datasource.url=${QUIZ_DB_URL:jdbc:postgresql://localhost:5433/quiz_service}
spring.datasource.username=${QUIZ_DB_USERNAME:quiz_user}
spring.datasource.password=${QUIZ_DB_PASSWORD:quiz_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
